version: "3.7"

services:
  redis:
    image: redis:alpine
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "3030:5432"
    user: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe-example
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/stripe-dev
      - /stripe-dev/node_modules
    environment:
      STRIPE_SECRET:
      REDIS: redis
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

volumes:
  pgdata: